### ISSUE TITLE
Question about Output for hwZero

### ISSUE THREAD

**Issue by amonjaraz** [uhcs2320/hwZero#1]
I am confused about the output requested for the homework assignment. In the section "Output", the second sentence states 

> " The first column is the time, the second is the name of the person, the third is the duration, and the fourth is the status. ". 

Does anyone know what that sentence is asking for and could you provide a simple example. 
Thank you,
Alex

**Comment by dfatimazohra** [comment]
The first part of the "Output" section is wrong. It's going to be updated by the professor soon.

Thanks,
Fatima Zohra
