### ISSUE TITLE
Program is not working correctly on Linux server.

### ISSUE THREAD

**Issue by doanHa** [uhcs2320/hwZero#14]
My code works perfectly fine on my laptop for all three test cases and also the example from the instruction, but when I uploaded onto the server, it would not run correctly. One function would not work correctly occasionally. I use visual studio 2015.
What might causes this problem?

**Comment by Akshay199456** [comment]
If you don't mind, could you be more specific as to what purpose that function served as well as expand on not running correctly?

**Comment by doanHa** [comment]
The function is std::string compare().
Comparing the word at the end of the line to the exact same word won't return 0. 
I figure it would be a special character such as '\n' or '\r', but trimming it will make my code go into an infinite loop.

**Comment by aleman** [comment]
Make sure that you use the correct parameter.
Some functions work on: string
Remember that string is different than: char *

For example, sending a variable of type: char *
as a parameter that is expecting: string
may give you unexpected results.

**Comment by doanHa** [comment]
I got it.  Thank you.
