### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by vlykarye** [uhcs2320/hwZero#23]
Ok. I'm new to git, but most of it is pretty self-explanatory. I watched the repo to get notifications of the commits. However, it appears we get notifications of literally everything whether or not we want them. I have been able to find the "unsubscribe" button for a few different pages here and there. But somehow, more notifications that are not commits still seem to pop up. The notification system seems to be lacking some obvious features. So, may I propose that emails be sent out every other day with information on the commits? I think we all need to know when the homework randomly changes from day to day. But 
(and this may just be me) I don't think anyone cares about random comments/issues/pull requests that do not concern #1 the homework assignment, and #2 our grades. Since there isn't an easy way to set up notifications, please consider an email route.

Also, why do I receive every email from Akshay to you? Is there a way to stop receiving them? I'm really confused on how this notification thing works.

Thanks

**Comment by aleman** [comment]
Can you try clicking on the "Unwatch" button near the top-right?

It has 3 choices; it seems that the default is the one where you get ALL notifications. 
Try changing it to either of the other 2 options (one of them is "ignore all".

**Comment by vlykarye** [comment]
My understanding is that "unwatching" the repo will stop all notifications, which renders using github pointless.

**Comment by aleman** [comment]
Not exactly.  There are 3 options on "Unwatching", it is like a drop-down list, click on it, and (for now) select:

  `"Not Watching" be notified when participating or @ mentioned`

We can try another setting for notifications via github (on next class).

**Comment by vlykarye** [comment]
Very well. I will try that option for now and see how it works.
