### ISSUE TITLE
"Numbers will have maximum of 10 digits."

### ISSUE THREAD

**Issue by vlykarye** [uhcs2320/hwZero#4]
The largest integer that can be stored is 4,294,967,295 on a 32 bit machine that doesn't support 64 bit addition (I would assume). Will we have to consider numbers larger than this, and/or is the server machine 64 bit? (It would take more effort to do.)

"The words and numbers may be separated by spaces, commas, period, new-line character, parenthesis, etc." Can we assume that each valid number and its category (m, h, d) will be separated by a space and only 1 space? If the separation can be more than 1 whitespace, then it would take considerably more effort to distinguish between certain situations such as "...since then, 100.days have passed..." and "...she went from 0 to 100. Days have passed since then." This particular situation would require that "minute, minutes, hour, hours, day, days" can start with capitol letters, but others might not.

**Comment by aleman** [comment]
No, you will not have to consider numbers larger than that.
