### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by doanHa** [uhcs2320/hwZero#5]
I would like to have clarification on the input and the way it should be processed.
1.  If the line says "They left at 12.5 minutes later, they came back." with 2 sentences being separated by just a period and not a space, would that 5 be added to variable minute(s)? Or can we assume there would be no such cases.
2. If, for example, "24 minutes" is written into two lines, such as 
They left 24
minutes ago.
Would 24 be added to variable minute(s)? Or can we also assume there would be no such cases.

**Comment by Akshay199456** [comment]
Hi,
1. I asked the professor in class and he replied that the minutes, days and hours will only take integer values. Also, the information is posted under hw0.

![image](https://cloud.githubusercontent.com/assets/11953567/18227045/136b176e-71de-11e6-9b06-ae78d2618785.png)

He has also added what the valid separators are:

![image](https://cloud.githubusercontent.com/assets/11953567/18227083/f4eb37f0-71de-11e6-88a8-458f668134e1.png)

![image](https://cloud.githubusercontent.com/assets/11953567/18227086/fc7e1f96-71de-11e6-9396-34a7169dc28a.png)

For the second question,  there would not be any such cases.

![image](https://cloud.githubusercontent.com/assets/11953567/18227052/3a910970-71de-11e6-8d2e-9b57ff9e8c70.png)

Hope that helps...

**Comment by vlykarye** [comment]
Will numbers (i.e 12), that need to be counted, be separated from their category (i.e minutes) word by only a space or not?

"You can assume that these are the separators that you must consider: space, comma, semicolon, left parenthesis, and right parenthesis." -- **This line doesn't make sense.**
"4, minutes" or "6; hours" or "20(minutes)?" etc doesn't make logical sense to me.

Please clarify this soon, otherwise, I will assume that valid numbers will only be separated by a space from their category word.

Thanks!

**Comment by doanHa** [comment]
To Akshay199456,
Thank you for your answer.
Though in my question 1, what I meant was, if the two sentences "They left at 12." and "5 minutes later, they came back" is written together on one line and is not separated by any space, should that 5 still being counted in the the variable minute(s)?

**Comment by vlykarye** [comment]
Um. lol..
"Examples of numbers that are not valid....."
"It took 12.67 minutes to form an opinion."

I think that question was validly answered.

**Comment by aleman** [comment]
To @doanHa , 
if it is a sentence such as `They left at 12. 5 minutes later, they came back`, then the space between the `12.` and the `5` allows the `5` to be a valid number, and it will be counted in the variable for minutes.
If there were no space between the 12 and the 5, such as `They left at 12.5 minutes later, they came back`, then as far as your code is concerned, no valid number was found.

**Comment by aleman** [comment]
To @vlykarye ,

Yes, numbers separated by their category will be separated by a space.

Your code will not be tested with things such as `5;days` or `4,hours` 

Your code may be tested with things such as `They were early (20 minutes) and hungry.`
or `Away for 3 hours, then returned`
These are valid things that your code should pick up and add up as needed. 

People that choose to utilize a tokenizer (which is optional), may recognize that they need to specify separators or delimiters. Hence the comment about separators in the description of the assignment.

**Comment by aleman** [comment]
I'm closing this issue, but in case that there are further questions, please ask again.
